# Generated by Django 3.1.7 on 2021-03-23 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 11, 4, 17, 97179), verbose_name='fecha de publicación'),
        ),
    ]
